version: v1.0
name: ''
agent:
  machine:
    type: e1-standard-2
    os_image: ubuntu2004
services:
  web:
    build: .
    ports:
      - '8080:8080'
    volumes:
      - '.:/code'
      - 'logvolume01:/var/log'
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
blocks: []
